### PR TITLE
2 sum problem in java

### PR DESCRIPTION
**Pull request by pratik-123**

### CODE REVIEW

**Comment by ShubhamPaliwal03** [comment]
Please assign this to me

**Comment by pratik-123** [comment]
@ShubhamPaliwal03 I don't see the assign or review section

**Comment by pratik-123** [comment]
@ShubhamPaliwal03 any update?

**Comment by ShubhamPaliwal03** [comment]
I didn't get assigned with that issue, so I can't create a pull request for
it.

**Review by yashwantaditya009 — APPROVED** [review]

**Pull request merged**
